services:
#    api.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    api.default_controller:
        class: ApiBundle\Controller\DefaultController
        arguments: ["@app.hospital_repository"]
        parent: "app.base_controller"